### ISSUE TITLE
Mac OSX make error

### ISSUE THREAD

**Issue by russlamb** [monacoinproject/monacoin#27] opened 2018-01-18 13:12 UTC
### Describe the issue
following the osX build notes results in errors.  

#### If so, please list the steps to reproduce below:
after installing brew dependencies

1. run ./autogen.sh
2. run ./confugure
3. run make

### Expected behaviour
make to complete successfully

### Actual behaviour
error

### What version of litecoin-core are you using?
0.14

### Machine specs:
- OS: 10.12.6

### Any extra information that might be useful in the debugging process.
error output from make 
https://pastebin.com/NVTNudtf

**Comment by hakemimi** [comment] 2018-01-19 08:17
This is caused by functors `operator()()` not marked `const` in many classes inside this repo. Usually all `operator()(T const& arg)` must be defined `operator()(T const& arg) const` to satisfy std-compliant algos like boost (> 1.66) 

I believe this is fixed in https://github.com/bitcoin/bitcoin/commit/1ec0c0a01c316146434642ab2f14a7367306dbec

**Closed as completed** 2018-01-26 03:47 UTC
